### ISSUE TITLE
인증방식

### ISSUE THREAD

**Issue by LandWhale2** [LandWhale2/open-api-design#4]
인증방식

**Comment by taxijjang** [comment]
## 사용자가 api key를 직접 발급

- api key (인증), secret key (인가)
- api key 구성요소
> - 거래소 data + time stamp 를 sha 256 해쉬를 이용하여 암호화

- secret key 구성요소
> - 회원 정보(id, password, 전화번호 등등) + time stamp 를 sha 256 해쉬를 이용하여 암호화

- Table 생성
|member_id|api_key|secret_key|
|------------|--------|------------|

**Comment by LandWhale2** [comment]
# API Key, Secret Key 이용

## 사용자의 Key 발급

### 1. 특정 인증 레벨 이상 사용자만 가능

### 2. 거래 금지 또는 계정 금지 사용자 X

---

## Parameter

Authorization (JWT Token) 방식 X,

JSON 으로 Key 값을 넘겨줌

- Public Basic Parameter JSON
```
{
    "api key": "",
}
```

- Private Basic Parameter JSON
```
{
    "api key": "",
    "secret key": "",
}
```


---

### API Key, Secret Key 테이블 생성

- 테이블 값 : key, mem_id, 생성시간, 호출횟수(호출제한 위해서)

---

# API, Secret Key 암호화 방식

## 1. API Key (Authentication)

- (User ID 또는 Email 또는 mem_id) + (생성 당시 시간)  해당 문자열 SHA256 Hash 암호화

## 2. Secret Key (Authorization)

- (API Key) + (랜덤한 문자 또는 숫자 [A-Z],[0-9][1~3 자리]) + 다른 고유한 값(email, mem_id, 전화번호)
